Simar/practice app
bounswe/bounswe2023group3 pull request #60
Opened 2023-05-10 18:44 UTC by simarahmtkhy

I have created the initial version of my app. Also I have made the necessary changes to the home html.

2023-05-10 19:08 UTC, Alputer commented
I guess we need to manage dependencies via requirements.txt file. I couldn't easily handle dependincy issues in my local file. Esad stated this issue [here](https://github.com/bounswe/bounswe2023group3/pull/57) as well.

2023-05-10 19:13 UTC, simarahmtkhy commented
Yes, you are right. I have updated the requirements.txt file accordingly. Can you check it?

2023-05-10 20:13 UTC, Alputer commented
I have tested and it seems to be satisfy all the requirements. I couldn't see any bug or unusual behaviour.

2023-05-10 20:14 UTC, Alputer approved these changes

2023-05-11 07:21 UTC, eyusufatik requested changes

2023-05-11 07:21 UTC, eyusufatik commented on practice-app/predictionPoll/db.sqlite3
Please remove db.sqlite file from your commit 

It might break other people local db if migrations dont work as intended.

We should also ignore it in the .gitingore file

2023-05-11 08:06 UTC, eyusufatik approved these changes

2023-05-11 15:30 UTC, merged